#!/bin/bash

ENDPOINT="https://lrs.adlnet.gov/xapi/statements"

# Have bash encode the credentials to base64
USER="xapi-tools"
PASS="xapi-tools"
AUTH=$(echo -n "$USER:$PASS" | base64)

I=0
ENABLED=false

echo "if beacon time on reaches 15, statement will be sent"

while read line; do
  # All this does is check whether the beacon with this UUID is on
  if [[ $(echo $line | grep "2F234454-CF6D-4A0F-ADF2-F4911BA9FFA6") ]]; then

    I=$((I+1))
    
    if [[ $I == 15 && $ENABLED == false ]]; then

      ENABLED=true

      STMT='{
          "actor": {
              "mbox": "mailto:tyler.mulligan.ctr@adlnet.gov",
              "name": "EMT_001",
              "objectType": "Agent"
          },
          "verb": {
              "id": "http://adlnet.gov/expapi/verbs/initialized",
              "display": {
                  "en-US": "initialized"
              }
          },
          "object": {
              "id": "http://adlnet.gov/expapi/activities/beacon",
              "definition": {
                  "name": {
                      "en-US": "beacon_tag"
                  },
                  "description": {
                      "en-US": "beacon_tag is operating"
                  }
              },
              "objectType": "Activity"
          }
      }'

      curl -i -X POST -H "X-Experience-API-Version: 1.0.1" -H "Authorization: Basic $AUTH" --data-binary "$STMT" $ENDPOINT

    fi

    if [[ $I == 100 ]]; then
      I=0
    fi
  else
    I=$((I-1))
    if [[ $I == -40 && $ENABLED == true ]]; then

      ENABLED=false

      STMT='{
          "actor": {
              "mbox": "mailto:tyler.mulligan.ctr@adlnet.gov",
              "name": "EMT_001",
              "objectType": "Agent"
          },
          "verb": {
              "id": "http://adlnet.gov/expapi/verbs/terminated",
              "display": {
                  "en-US": "terminated"
              }
          },
          "object": {
              "id": "http://adlnet.gov/expapi/activities/beacon",
              "definition": {
                  "name": {
                      "en-US": "beacon_tag"
                  },
                  "description": {
                      "en-US": "beacon_tag has bee disabled"
                  }
              },
              "objectType": "Activity"
          }
      }'

      curl -i -X POST -H "X-Experience-API-Version: 1.0.1" -H "Authorization: Basic $AUTH" --data-binary "$STMT" $ENDPOINT

    fi

    if [[ $I == -100 ]]; then
      I=0
    fi
  fi

  echo $I

done
