#!/bin/bash

ENDPOINT="https://lrs.adlnet.gov/xapi/statements"

# Have bash encode the credentials to base64
USER="xapi-tools"
PASS="xapi-tools"
AUTH=$(echo -n "$USER:$PASS" | base64)

while read line; do
  # All this does is check whether the beacon with this UUID is on
  if [[ $(echo $line | grep "2F234454-CF6D-4A0F-ADF2-F4911BA9FFA6") ]]; then

    STMT='{
        "actor": {
            "mbox": "mailto:tyler.mulligan.ctr@adlnet.gov",
            "name": "Tyler",
            "objectType": "Agent"
        },
        "verb": {
            "id": "http://example.com/verbs/scanned",
            "display": {
                "en-US": "scanned"
            }
        },
        "object": {
            "id": "http://adlnet.gov/expapi/activities/beacon",
            "definition": {
                "name": {
                    "en-US": "Beacon"
                },
                "description": {
                    "en-US": "A BLE Beacon"
                }
            },
            "objectType": "Activity"
        }
    }'

    curl -i -X POST -H "X-Experience-API-Version: 1.0.1" -H "Authorization: Basic $AUTH" --data-binary "$STMT" $ENDPOINT

    exit 0

  fi
done
